version: '3.8'

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    container_name: otp-server-postgres
    environment:
      POSTGRES_DB: otp_server_db
      POSTGRES_USER: otp_server_user
      POSTGRES_PASSWORD: otp_server_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otp_server_user -d otp_server_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - otp-network

  redis:
    image: redis:7
    container_name: otp-server-redis
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10 --save 60 10000
    environment:
      - REDIS_MAXMEMORY=2gb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - otp-network

  otp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otp-server-app
    environment:
      - ENVIRONMENT=development
      - SERVER_PORT=8080
      - DB_PROVIDER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=otp_server_user
      - POSTGRES_PASSWORD=otp_server_password
      - POSTGRES_DB=otp_server_db
      - POSTGRES_SSL_MODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_DURATION=1m
      - RATE_LIMIT_OTP_REQUESTS=3
      - RATE_LIMIT_OTP_DURATION=10m
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - otp-network

volumes:
  postgres_data:
  redis_data:

networks:
  otp-network:
    driver: bridge
    name: otp-server-network 